# Generated by Django 3.0.3 on 2020-04-08 07:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 7, 42, 28, 539207, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 7, 42, 28, 538204, tzinfo=utc)),
        ),
    ]
