# Generated by Django 3.0.3 on 2020-04-09 10:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200408_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 10, 5, 14, 740572, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 10, 5, 14, 739572, tzinfo=utc)),
        ),
    ]
